Traceback (most recent call last):
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 355, in parameter_run
    energies[(param.alpha, param.beta)]
KeyError: (0.16, 0.64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/solutions.py", line 239, in baroclinic_flow
    with open(sln_dir, "rb") as inp:
FileNotFoundError: [Errno 2] No such file or directory: 'Baroclinic/Functions/Domain=1300kmx1300km_OceanDepth=4000m_ShelfDepth=200m_ShelfWidth=100km_SlopeWidth=50km_CanyonWidth=20.0km_alpha=0.16_beta=0.64_domainpadding=350km_dampingwidth=150km_sponge=(350.0km,350km)_width=150km_N=3.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 463, in <module>
    parameter_run(
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 358, in parameter_run
    barotropic_solution, baroclinic_solution = startup(
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 232, in startup
    baroclinic_solutions = solutions.baroclinic_flow(
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/solutions.py", line 283, in baroclinic_flow
    fem = pickle.load(inp)
EOFError: Ran out of input
